# APPLICATION CONFIG
spring.application.name=log-intelligence-engine

# OPENAI CONFIG
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

# LOGGING CONFIG
logging.level.root=INFO
logging.level.com.princeagrawal.ai=DEBUG